// SPDX-License-Identifier: MIT
// Copyright © 2026 class-dump contributors. All rights reserved.

import Testing

@testable import ClassDumpCore

@Suite("ClassDumpHeaderVisitor Tests")
struct ClassDumpHeaderVisitorTests {
    @Test("ClassDumpHeaderVisitor header generation")
    func headerVisitorGeneration() {
        let header = ClassDumpHeaderVisitor.generateHeader(
            generatedBy: "test-tool",
            version: "1.0"
        )

        #expect(header.contains("Generated by test-tool 1.0"))
        #expect(header.contains("Copyright"))
    }

    @Test("ClassDumpHeaderVisitor without version")
    func headerVisitorNoVersion() {
        let header = ClassDumpHeaderVisitor.generateHeader(
            generatedBy: "class-dump"
        )

        #expect(header.contains("Generated by class-dump"))
        #expect(!header.contains("1.0"))
    }
}
